<?php $app = Zend_Registry::get("appData"); ?>

<!DOCTYPE html>
<html lang="es-cl">
	<head>
	
	
		<meta charset="utf-8">
		<title> <?php echo $app["name"] ?> </title>
		<meta name="description" content="">
		<meta name="author" content="">
			
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
		
		<link rel="stylesheet" type="text/css" media="screen" href="/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" media="screen" href="/css/font-awesome.min.css">

		<link rel="stylesheet" type="text/css" media="screen" href="/css/smartadmin-production-plugins.min.css">
		<link rel="stylesheet" type="text/css" media="screen" href="/css/smartadmin-production.min.css">
		<link rel="stylesheet" type="text/css" media="screen" href="/css/smartadmin-skins.min.css">

		<link rel="stylesheet" type="text/css" media="screen" href="/css/smartadmin-rtl.min.css"> 

		<link rel="shortcut icon" href="<?php echo $app['favicon'] ?>" type="image/x-icon">
		<link rel="icon" href="<?php echo $app['favicon'] ?>" type="image/x-icon">

		<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700">
		<link rel="apple-touch-icon" href="/img/splash/sptouch-icon-iphone.png">
		<link rel="apple-touch-icon" sizes="76x76" href="/img/splash/touch-icon-ipad.png">
		<link rel="apple-touch-icon" sizes="120x120" href="/img/splash/touch-icon-iphone-retina.png">
		<link rel="apple-touch-icon" sizes="152x152" href="/img/splash/touch-icon-ipad-retina.png">
		
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="apple-mobile-web-app-status-bar-style" content="black">
		
		<link rel="apple-touch-startup-image" href="/img/splash/ipad-landscape.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape)">
		<link rel="apple-touch-startup-image" href="/img/splash/ipad-portrait.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait)">
		<link rel="apple-touch-startup-image" href="/img/splash/iphone.png" media="screen and (max-device-width: 320px)">
	
		
		<link rel="stylesheet" type="text/css" media="screen" href="/css/rice.css">

		<?php  echo $this->headLink(); ?>

		
	</head>

	<body class="smart-style-1">

		<!-- #HEADER -->
		<header id="header">
			<div id="logo-group">
				<!-- PLACE YOUR LOGO HERE -->
				<span id="logo"> <a href="/admin"><img src="<?php echo $app['logo'] ?>" alt="<?php echo $app["name"] ?>"></a> </span>
				<!-- END LOGO PLACEHOLDER -->
			</div>

			<!-- pulled right: nav area -->
			<div class="pull-right">
				
				<!-- collapse menu button -->
				<div id="hide-menu" class="btn-header pull-right">
					<span> <a href="javascript:void(0);" data-action="toggleMenu" title="Collapse Menu"><i class="fa fa-reorder"></i></a> </span>
				</div>
				<!-- end collapse menu -->

				<div id="logout" class="btn-header transparent pull-right">
					<span> <a href="/admin/logout" title="Sign Out" data-action="userLogout" data-logout-msg="You can improve your security further after logging out by closing this opened browser"><i class="fa fa-sign-out"></i></a> </span>
				</div>

				<!-- search mobile button (this is hidden till mobile view port) -->
				<div id="search-mobile" class="btn-header transparent pull-right">
					<span> <a href="javascript:void(0)" title="Search"><i class="fa fa-search"></i></a> </span>
				</div>
				<!-- end search mobile button -->
				<div id="fullscreen" class="btn-header transparent pull-right">
					<span> <a href="javascript:void(0);" data-action="launchFullscreen" title="Full Screen"><i class="fa fa-arrows-alt"></i></a> </span>
				</div>

			</div>

		</header>
		<aside id="left-panel">

			<!-- User info -->
			<div class="login-info">
				<span> 
					<!--<a href="javascript:void(0);" id="show-shortcut" data-action="toggleShortcut">
						<img src="/img/avatars/sunny.png" alt="me" class="online" /> 
						<span>
							john.doe 
						</span>
						<i class="fa fa-angle-down"></i>
					</a> -->
				</span>
			</div>

			<nav>

				

	<!-- Menu principal-->

	
	<?php
		$var = $this->navigation();
		if($var instanceof Zend_View_Helper_Navigation){
			$helper = $var->findHelper("menuNew");
			if($helper instanceof Zend_View_Helper_Navigation_Menu){
				echo ($helper->renderMenu($var->getContainer(),
                    array("ulClass"=>"","ulClassDeepest"=>"",
                    "ulId"=>"nav")));
			}
		}?>
	</nav>
	<!-- end Menu principal -->


		</aside>
		<!-- END NAVIGATION -->
		
		<div id="main" role="main" ng-app="riceApp" >
			<!-- MAIN CONTENT -->
			<div id="content"  ng-cloak >
				<?php echo $this->layout()->content; ?>
			</div>
			<!-- END MAIN CONTENT -->
		</div>

		<!--<div id="shortcut">
			<ul>
				<li>
					<a href="/admin/profile" class="jarvismetro-tile big-cubes selected bg-color-pinkDark"> <span class="iconbox"> <i class="fa fa-user fa-4x"></i> <span>My Profile </span> </span> </a>
				</li>
			</ul>
		</div>-->

		<!-- PACE LOADER - turn this on if you want ajax loading to show (caution: uses lots of memory on iDevices)-->
		<script data-pace-options='{ "restartOnRequestAfter": true }' src="/js/plugin/pace/pace.min.js"></script>

		<!-- Link to Google CDN's jQuery + jQueryUI; fall back to local -->
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
		<script>
			if (!window.jQuery) {
				document.write('<script src="/js/libs/jquery-2.1.1.min.js"><\/script>');
			}
		</script>

		<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
		<script>
			if (!window.jQuery.ui) {
				document.write('<script src="/js/libs/jquery-ui-1.10.3.min.js"><\/script>');
			}
		</script>

		<script src="/js/app.config.js"></script>
		<script src="/js/plugin/jquery-touch/jquery.ui.touch-punch.min.js"></script> 
		<script src="/js/bootstrap/bootstrap.min.js"></script>
		<script src="/js/notification/SmartNotification.min.js"></script>
		<script src="/js/smartwidgets/jarvis.widget.min.js"></script>
		<script src="/js/plugin/easy-pie-chart/jquery.easy-pie-chart.min.js"></script>
		<script src="/js/plugin/sparkline/jquery.sparkline.min.js"></script>
		<script src="/js/plugin/jquery-validate/jquery.validate.min.js"></script>
		<script src="/js/plugin/masked-input/jquery.maskedinput.min.js"></script>
		<script src="/js/plugin/select2/select2.min.js"></script>
		<script src="/js/plugin/bootstrap-slider/bootstrap-slider.min.js"></script>
		<script src="/js/plugin/msie-fix/jquery.mb.browser.min.js"></script>
		<script src="/js/plugin/fastclick/fastclick.min.js"></script>
		<script src="/js/plugin/fastclick/fastclick.min.js"></script>
		<script src="/js/app.min.js"></script>
		<script src="/js/plugin/highcharts/highcharts.js"></script>
		
		<script type="text/javascript">
			$(document).ready(function() {
				 pageSetUp();
				 $("#nav > li.open > #nav").show();
			})
		</script>


		<script src="/bower_components/angular/angular.min.js"></script>
		<script src="/bower_components/angular-resource/angular-resource.min.js"></script>
		<script src="/bower_components/angular-animate/angular-animate.min.js"></script>
		
		<script src="/bower_components/angular-bootstrap/ui-bootstrap.min.js"></script>
		<script src="/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js"></script>

		<link rel="stylesheet" type="text/css" media="screen" href="/bower_components/angular-loading-bar/build/loading-bar.min.css">
		<script src="/bower_components/angular-loading-bar/build/loading-bar.min.js"></script>

		<link rel="stylesheet" href="/bower_components/ng-table-bundle/ng-table.min.css">
		<script src="/bower_components/ng-table-bundle/ng-table.min.js"></script>

		<script src="/bower_components/ng-file-upload/ng-file-upload.min.js"></script>

		<?php  echo $this->headScript(); ?>

	</body>

</html>