<div class="container-fluid menu-section container-modal borde-modal"> 
	<div class="row padding-top-row-modal" >
		<div class="col-md-1 "></div>
		<div class="col-md-11">
    		<h1 class="modal-title" id="modal-title">Atención!</h1>
		</div>
	</div>
	<div class="row " >
		<div class="col-md-2 "></div>
		<div class="col-md-10">
  			<h3>Esta seguro de que desea continuar?</h3> 
		</div>
	</div>
	<div class="row padding-top-row-modal" ><div class="col-md-12"></div></div>
	<div class="row padding-top-row-modal" ><div class="col-md-12"></div></div>
	<div class="row padding-top-row-modal" >
		<div class="col-md-1"></div>
		<div class="col-md-4"><button class="btn btn-primary btn-lg btn-block" type="button" ng-click="aceptar()">Continuar</button></div>
		<div class="col-md-2"></div>
		<div class="col-md-4"><button class="btn btn-danger btn-lg btn-block" type="button" ng-click="cancelar()">Cancelar</button></div>
		<div class="col-md-1"></div>
	</div>	
	<div class="row padding-top-row-modal" ><div class="col-md-12"></div></div>
	<div class="row padding-top-row-modal" ><div class="col-md-12"></div></div>
</div>