<div ng-controller="EstadisticasCrtl">

	<ol class="breadcrumb">
		<li>Tablero de control</li>
		<li>Estadisticas</li>
	</ol>

	<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12 sortable-grid ui-sortable">
		<div class="jarviswidget jarviswidget-sortable" id="wid-id-7" data-widget-editbutton="false" role="widget">
			<header role="heading">
				<span class="widget-icon"> <i class="fa fa-bar-chart-o"></i> </span>
				<h2>Ventas de la semana</h2>				
				<span class="jarviswidget-loader"><i class="fa fa-refresh fa-spin"></i></span>
			</header>
			<div role="content">
				<div class="widget-body no-padding">
					<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
				</div>
			</div>
		</div>
	</article>

</div>