<div id="content" class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3 hidden-xs hidden-sm"></div>
        <div class="col-xs-12 col-sm-12 col-md-5 col-lg-4">
            <div class="well no-padding">   
                <form action="" id="login-form" class="smart-form client-form" method="post">
                    <header>
                        Inicio de sesion
                    </header>
                    <fieldset>
                        <section>
                            <label class="label">Username</label>
                            <label class="input"> <i class="icon-append fa fa-user"></i>
                                <input type="text" name="username" id="username">
                        </section>
                        <section>
                            <label class="label">Password</label>
                            <label class="input"> <i class="icon-append fa fa-lock"></i>
                                <input type="password" name="password" id="password">
                        </section>
                    </fieldset>
                    <footer>
                        <div class="alert alert-block alert-danger" id="errorLogin" style="display:none">
                            <h4 class="alert-heading"> Error de login!</h4>
                            <p >
                                Username o password no corresponden
                            </p>
                        </div>
                        <img src="/img/32.gif" id="loading" style="display:none">
                        <button type="button" class="btn btn-primary"  onClick='enviar()'>
                            Aceptar
                        </button>
                    </footer>
                </form>
            </div>
        </div>
    </div>
</div>
