<div ng-controller="OrdenesCrtl">

	<ol class="breadcrumb">
		<li>Pedidos</li>
		<li>Ordenes</li>
	</ol>
	
	<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12 sortable-grid ui-sortable">
		<div class="jarviswidget jarviswidget-color-darken jarviswidget-sortable " role="widget">
			<header role="heading">
				<span class="widget-icon"> <i class="fa fa-table"></i> </span>
				<h2>Listado de pedidos </h2>
			</header>
			<div role="content" class="contentTable">
				<div align="right">

					<div class="row">
						<div class="col-md-2">
							<div align="left"> Desde:</div>
							<p  class="input-group" ng-init="fechaDesde = false">
								<input type="text" class="form-control" 
									uib-datepicker-popup="{{format}}" 
									ng-model="dtDesde" is-open="fechaDesde" datepicker-options="dateOptionsDesde" 
									ng-required="true" close-text="Close"  show-button-bar="false"
									 ng-change="changeFecha()"/>
								<span class="input-group-btn">
									<button type="button" class="btn btn-default" ng-click="fechaDesde = !fechaDesde"><i class="glyphicon glyphicon-calendar"></i></button>
								</span>
							</p>
						</div>
						<div class="col-md-2">
							<div align="left"> Hasta:</div>
							<p class="input-group" ng-init="fechaHasta = false">
								<input type="text" class="form-control" 
									uib-datepicker-popup="{{format}}"  ng-model="dtHasta" is-open="fechaHasta" datepicker-options="dateOptionsHasta" 
									ng-required="true" close-text="Close" show-button-bar="false"  ng-change="changeFecha()"/>
								<span class="input-group-btn">
									<button type="button" class="btn btn-default" ng-click="fechaHasta = !fechaHasta"><i class="glyphicon glyphicon-calendar"></i></button>
								</span>
							</p>
						</div>
						<div class="col-md-8">
							<!--<button class="btn btn-primary" ng-click="nuevo()" ><i class="fa fa-plus"></i>Nuevo</button>-->
						</div>
					</div>
					
				</div>
				<table ng-table="tableParams" class="table table-striped table-bordered table-hover dataTable no-footer" show-filter="true">
					<tr ng-repeat="(k,row) in $data">
						<td title="'Fecha creacion'" filter="{ fecha_creacion: 'text'}" sortable="'fecha_creacion'">{{row.fecha_creacion}}</td>

						<td title="'Total'" filter="{ total: 'text'}" sortable="'total'">{{row.total | currency:"$":0}}</td>

						<td title="'Estado'" align="center">
							<span ng-if="row.estado == <?php echo Pedido::ESTADO_1_PENDIENTE ?>" class="label label-danger">Pendiente</span>
							<span ng-if="row.estado == <?php echo Pedido::ESTADO_2_ACEPTADO ?>" class="label label-info">Aceptado</span>
							<span ng-if="row.estado == <?php echo Pedido::ESTADO_3_EN_PREPARACION ?>" class="label label-warning">En preparacion</span>
							<span ng-if="row.estado == <?php echo Pedido::ESTADO_4_DESPACHADO ?>" class="label label-success">Despachado</span>
							<span ng-if="row.estado == <?php echo Pedido::ESTADO_5_RECHAZADO ?>" class="label label-default">Rechazado</span>
						</td>

						<td title="'Acciones'" align="center">
							<button class="btn btn-warning" title="Ver detalle"  ng-click="verDetalle(row.id)"> 
								<i class="fa fa-search"></i> 
							</button>
							<button ng-if="row.estado == 3" class="btn btn-success" title="Despachar"  ng-click="despachar(row.id)"> 
								<i class="fa fa-check"></i> 
							</button>
						</td>
					</tr>
				</table>

			</div>
		</div>

	</article>
</div>

<script type="text/ng-template" id="verDetallePedido.html">

	<div class="modal-header">
		<h3 class="modal-title" id="modal-title">
  			Detalle del pedido
		</h3>
	</div>
	<div class="modal-body" id="modal-body">

		<form class="smart-form">
			<fieldset>
				<section>
					<label class="input">
						<strong>Nombre:</strong> <span>{{data.detalle.cliente.persona.nombres}}
						{{data.detalle.cliente.persona.ap_pat}}
						{{data.detalle.cliente.persona.ap_mat}}</span>
					</label>
					<label class="input">
						<strong>Celular:</strong> <span>{{data.detalle.cliente.persona.celular}}</span>
					</label>
					<label class="input">
						<strong>Email:</strong> <span>{{data.detalle.cliente.persona.email}}</span>
					</label>
					<label class="input">
						<strong>Username:</strong> <span>{{data.detalle.cliente.username}}</span>
					</label>
				</section>
			</fieldset>
			<fieldset>
				<section>
					<label class="input">
						<strong>Direccion:</strong> <span>{{data.detalle.direccion.descripcion}}</span>
					</label>
					<label class="input">
						<strong>Sector:</strong> <span>{{data.detalle.direccion.sector.descripcion}}</span>
					</label>
				</section>
			</fieldset>
			<fieldset>
				<section>
					<label class="input">
						<strong>Observacion:</strong> <span>{{data.detalle.observacion}}</span>
					</label>
				</section>
			</fieldset>

			<fieldset>
				<table class="table table-bordered">
					<tr>
						<th>Producto</th>
						<th>Especificacion</th>
					</tr>
					<tr  ng-repeat="(key, pp) in data.detalle.productos">
						<td>{{pp.producto.nombre}}</td>
						<td>
							<span ng-if="pp.especificacion.descripcion">{{pp.especificacion.descripcion}}</span>
							<span ng-if="!pp.especificacion.descripcion">-</span>
						</td>
					</tr>
				</table>
				
			</fieldset>

			<fieldset>
				<section>
					<label class="input">
						<strong>Total:</strong><span>{{data.detalle.total | currency:"$":0}}</span>
					</label>
				</section>
			</fieldset>
		</form>		
	</div>
	<div class="modal-footer">

		<button ng-if="data.detalle.estado != 2 && data.detalle.estado != 4 && data.detalle.estado != 3" class="btn btn-primary" type="button" ng-click="aceptar(1)">Aceptar</button>
		
		<button  ng-if="data.detalle.estado != 5 && data.detalle.estado != 4"  class="btn btn-danger" type="button" ng-click="aceptar(5)">Rechazar</button>

		<button  ng-if="data.detalle.estado == 3"  class="btn btn-success" type="button" ng-click="aceptar(4)">Despachar</button>

		<button class="btn btn-warning" type="button" ng-click="cancelar()">Cancelar</button>
	</div>

</script>