<div ng-controller="ReportesCrtl">

	<ol class="breadcrumb">
		<li>Pedidos</li>
		<li>Reportes</li>
	</ol>
	
	<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12 sortable-grid ui-sortable">
		<div class="jarviswidget jarviswidget-color-darken jarviswidget-sortable " role="widget">
			<header role="heading">
				<span class="widget-icon"> <i class="fa fa-table"></i> </span>
				<h2>Listado de venta por dia </h2>
			</header>
			<div role="content" class="contentTable">
				<div align="right">
					<div class="row">
						<div class="col-md-2">
							<div align="left"> Desde:</div>
							<p  class="input-group" ng-init="fechaDesde = false">
								<input type="text" class="form-control" 
									uib-datepicker-popup="{{format}}" 
									ng-model="dtDesde" is-open="fechaDesde" datepicker-options="dateOptionsDesde" 
									ng-required="true" close-text="Close"  show-button-bar="false"
									 ng-change="changeFecha()"/>
								<span class="input-group-btn">
									<button type="button" class="btn btn-default" ng-click="fechaDesde = !fechaDesde"><i class="glyphicon glyphicon-calendar"></i></button>
								</span>
							</p>
						</div>
						<div class="col-md-2">
							<div align="left"> Hasta:</div>
							<p class="input-group" ng-init="fechaHasta = false">
								<input type="text" class="form-control" 
									uib-datepicker-popup="{{format}}"  ng-model="dtHasta" is-open="fechaHasta" datepicker-options="dateOptionsHasta" 
									ng-required="true" close-text="Close" show-button-bar="false"  ng-change="changeFecha()"/>
								<span class="input-group-btn">
									<button type="button" class="btn btn-default" ng-click="fechaHasta = !fechaHasta"><i class="glyphicon glyphicon-calendar"></i></button>
								</span>
							</p>
						</div>
					</div>
				</div>
				<table ng-table="tableParams" class="table table-striped table-bordered table-hover dataTable no-footer" show-filter="true">
					<tr ng-repeat="(k,row) in $data">
						<td title="'Fecha'" filter="{ fecha: 'text'}" sortable="'fecha'">{{row.fecha}}</td>
						<td title="'Total'" filter="{ total: 'text'}" sortable="'total'">{{row.total | currency:"$":0}}</td>
					</tr>
				</table>
			</div>
		</div>
	</article>
</div>